name: full_web_converter_to_flutter_app_master
description: "A Flutter project converted from full web converter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.10.0
  webview_flutter: ^4.13.0
  firebase_messaging: ^16.0.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
